Feature test cases
sachind-cuelogic/BugManagementSystem pull request #6
Opened 2017-04-11 12:28 UTC by sachind-cuelogic

Test cases of :
- Sign Up success and fail
- Login success and fail
- Create Project 
- Successfully redirect

2017-04-12 10:13 UTC, ananthu-nair707 requested changes
Please make these final changes to merge this code.

2017-04-12 10:13 UTC, ananthu-nair707 commented on bms/bms_app/models.py
> +    def __str__(self):
Why 2 __str__(self) functions for same model class?

2017-04-12 10:13 UTC, ananthu-nair707 commented on bms/bms_app/static/bms_app/js/prod_list.js
> +$(document).ready(function(){
Why 2 different document ready functions?

2017-04-12 10:13 UTC, ananthu-nair707 commented on bms/bms_app/tests.py
> +		user = User.objects.create_user('mahesh', 'mahesh@mail.com','mahesh123')
Remove hardcoded values.

2017-04-12 10:13 UTC, ananthu-nair707 commented on bms/bms_app/views.py
> +        return render(request, 'registration/create_product.html', {'users': users, 'roles': roles, 'prod_types': prod_types})
80 char rule.

2017-04-12 15:18 UTC, sachind-cuelogic commented on bms/bms_app/models.py
> +    def __str__(self):
I forgotted to remove First str(self) functions

2017-04-13 06:40 UTC, nileshm-cuelogic commented on bms/bms_app/static/bms_app/css/create_prodStyle.css
> +.createprod
Follow CSS naming conventions, and write reusable CSS, for reference check below link.
https://blog.toughbyte.com/blabla-9fd86eae4e6c

2017-04-13 06:40 UTC, nileshm-cuelogic commented on bms/bms_app/static/bms_app/css/create_prodStyle.css
> +#cancelbuton
Two words should be seperated by  "-" eg. cancel-button.
Button spelling is wrong

2017-04-13 06:46 UTC, nileshm-cuelogic commented on bms/bms_app/static/bms_app/css/create_prodStyle.css
> +#fileForm
Camel captioning should not be used in CSS.

2017-04-13 06:47 UTC, nileshm-cuelogic commented on bms/bms_app/static/bms_app/css/land_common.css
> +    display: table;
Display: table always takes 100% width, you don't have to specify it again.

2017-04-13 06:52 UTC, nileshm-cuelogic commented on bms/bms_app/static/bms_app/css/prod_list.css
> +    left: 250px;
you have given   left: 250px and margin:-250px, which is unnecessary

2017-04-13 06:53 UTC, nileshm-cuelogic commented on bms/bms_app/static/bms_app/css/prod_list.css
> +    background: none;
background:none is not valid CSS property.

2017-04-13 07:02 UTC, nileshm-cuelogic commented on bms/bms_app/static/bms_app/css/prod_list.css
> +    overflow-y: scroll;
for better user experience overflow should be given "auto" instead of "scroll"

2017-04-13 15:06 UTC, ananthu-nair707 approved these changes

2017-04-14 08:20 UTC, merged